# Generated by Django 4.2.3 on 2023-08-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookstoremodel',
            name='catagory',
            field=models.CharField(choices=[('Mystery', 'Mystery'), ('Islamic', 'Islamic'), ('Thriller', 'Thriller'), ('Sci-Fi', 'Sci-Fi'), ('Humor', 'Humor'), ('Horror', 'Horror')], max_length=30),
        ),
    ]
