# Generated by Django 4.2.3 on 2023-08-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_bookstoremodel_catagory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bookstoremodel',
            old_name='catagory',
            new_name='category',
        ),
    ]
